language: php
php:
  - '7.1'
before_install:
  - openssl aes-256-cbc -K $encrypted_a3d52ca1f4d7_key -iv $encrypted_a3d52ca1f4d7_iv -in deploy_key.enc -out deploy_key -d
install:
  - composer install
script: bash ./deploy.sh
env:
  global:
    - COMMIT_AUTHOR_EMAIL: "dawidloranc@gmail.com"
