# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: Dawid Loranc
subtitle: "What I can not create I do not understand." - Richard Feynman
url: https://dloranc.github.io

# Insert your disqus shortname
disqus:
   shortname: dloranc-github-io